#!/usr/bin/env bash

set -euo pipefail

if [[ ! -e .cabal-sandbox ]]; then
    cabal sandbox init
    cabal install shake
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  SELFDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$SELFDIR/$SOURCE"
done
SELFDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
cd $SELFDIR

export EUID

cabal exec runghc -- \
    -Wall \
    -rtsopts -with-rtsopts=-I0 \
    -XLambdaCase \
    Build.hs \
    --colour \
    "$@"

