#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# Parallel setup
###############################################################################

numCpus="$(grep -c "^processor" /proc/cpuinfo)"
jobs=""

stack build &
jobs+=" $!"

if [[ ! -e controller/.git ]]; then
    echo "Firmware directory not found. Updating submodules."
    git submodule init
    git submodule update &
    jobs+=" $!"
fi

for job in $jobs; do
    wait "$job"
done



###############################################################################
# Configure script dir
###############################################################################

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  SELFDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$SELFDIR/$SOURCE"
done
SELFDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
cd $SELFDIR



###############################################################################
# Run build script
###############################################################################

stack exec -- ergodox --colour "$@"
